apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
      - cluster: dev
        url: https://34.67.23.222
      - cluster: staging
        url: https://34.41.248.45
  template:
    metadata:
      name: 'ingress-nginx'
    spec:
      project: default
      sources:
      - chart: ingress-nginx
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: '3.4.3'
      destination:
        server: '{{.url}}'
        namespace: ingress-nginx
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true        
