apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - cluster: workloads-dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'ingress-nginx'
    spec:
      project: default
      source:
      - chart: ingress-nginx
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: '3.4.3'
      destination:
        server: '{{.url}}'
        namespace: ingress-nginx
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true        
