apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: exernal-secrets
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - clusters: {}
      # selector:
      #   matchLabels:
      #     staging: true
  template:
    metadata:
      name: 'external-secrets-{{.name}}'
      finalizers:
      - "resources-finalizer.argocd.argoproj.io"
    spec:
      project: default
      sources:
      - chart: external-secrets
        repoURL: https://charts.external-secrets.io
        targetRevision: 'v0.9.6'
        helm:
          parameters:
          - name: "installCRDs"
            value: "true"
      - repoURL: "https://github.com/SamPriyadarshi/argocd-bootcamp.git"
        targetRevision: HEAD
        path: 03-applicationset/external-secrets/config
      destination:
        name: '{{ .name }}'
        namespace: 'default'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
