# apiVersion: v1
# kind: Service
# metadata:
#   name: myservice
# spec:
#   ports:
#   - port: 80
#     protocol: TCP
#     targetPort: 80
#   selector:
#     app: myapp
#   sessionAffinity: None
#   type: LoadBalancer
